# Generated by Django 2.2.5 on 2020-01-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='state',
            field=models.CharField(choices=[('Free', 'Free'), ('Blocked', 'Blocked'), ('Unblocked', 'Unblocked')], default='Free', max_length=20),
        ),
    ]
