# Generated by Django 2.2.5 on 2020-01-26 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0002_auto_20200126_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alloted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('Free', 'Free'), ('Blocked', 'Blocked'), ('Unblocked', 'Unblocked')], default='Blocked', max_length=20)),
                ('keep_alive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
