# Generated by Django 2.2.5 on 2020-01-26 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0003_auto_20200126_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alloted',
            old_name='updated_at',
            new_name='allocated_at',
        ),
    ]
