# Generated by Django 2.2.5 on 2020-01-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0005_auto_20200126_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alloted',
        ),
    ]
