# Generated by Django 2.2.5 on 2020-01-26 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0011_auto_20200126_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='last_stay_alive',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
