# Generated by Django 2.2.5 on 2020-01-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0012_token_last_stay_alive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='last_stay_alive',
            new_name='last_alive',
        ),
    ]
